# Jupyterを触ってみる

100 numpy exercisesに触れながら、Jupyterもいじってみちゃう

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.11.2


In [3]:
v = np.zeros(10)
print(v)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [4]:
m = np.ones((5,5,5))
siz = m.size
cnt = m.itemsize
print("%d bytes (siz : %d, cnt : %d)" % (siz*cnt, siz, cnt) )

1000 bytes (siz : 125, cnt : 8)


In [5]:
np.info(np.add)  # python -c "import numpy as np; np.info(np.add)"とか

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


In [6]:
v = np.zeros(10)
v[4] = 1
print(v)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [7]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
v = np.arange(9)
m = v.reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
nonz = np.nonzero([1,2,0,0,4,0])
print(nonz)

(array([0, 1, 4], dtype=int64),)


In [11]:
m = np.eye(3)
print(m)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


ちなみに、identityでも同じことが出来るらしい。  
eyeだと列数指定も可能

In [12]:
m = np.random.random((3,3,3))
print(m)

[[[ 0.61911151  0.80198032  0.22463134]
  [ 0.99640787  0.0462281   0.36245522]
  [ 0.53004166  0.32085394  0.2684239 ]]

 [[ 0.50366836  0.78446471  0.8822636 ]
  [ 0.31008912  0.3721529   0.95085441]
  [ 0.72128777  0.67535474  0.14569065]]

 [[ 0.91028461  0.73480662  0.25460764]
  [ 0.4917047   0.42623424  0.54223453]
  [ 0.79533219  0.97056838  0.86800096]]]


In [13]:
m = np.random.random((10,10))
matMin, matMax = m.min, m.max
print(matMin, matMax)

<built-in method min of numpy.ndarray object at 0x00000000056AD8A0> <built-in method max of numpy.ndarray object at 0x00000000056AD8A0>


In [14]:
v = np.random.random(30)
mn = v.mean()
print(mn)

0.632848036376


In [15]:
m = np.ones((10,10))
m[1:-1,1:-1] = 0
print(m)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [16]:
m = np.ones((10,10))
m = np.pad(m, pad_width=1, mode='constant', constant_values=0)
print(m)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


なんで…？
最後のはたぶんCと同じ様な理由でしょうか。浮動小数点数の誤差

In [18]:
m = np.diag(1+np.arange(4), k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
m = np.zeros((8,8), dtype=int)
m[1::2,::2] = 1
m[::2,1::2] = 1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


この意味があんまりわかっていません…