# Jupyterを触ってみる

100 numpy exercisesに触れながら、Jupyterもいじってみちゃう

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.11.2


In [3]:
v = np.zeros(10)
print(v)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [4]:
m = np.ones((5,5,5))
siz = m.size
cnt = m.itemsize
print("%d bytes (siz : %d, cnt : %d)" % (siz*cnt, siz, cnt) )

1000 bytes (siz : 125, cnt : 8)


In [5]:
np.info(np.add)  # python -c "import numpy as np; np.info(np.add)"とか

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


In [6]:
v = np.zeros(10)
v[4] = 1
print(v)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [7]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
v = np.arange(9)
m = v.reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
nonz = np.nonzero([1,2,0,0,4,0])
print(nonz)

(array([0, 1, 4], dtype=int64),)


In [11]:
m = np.eye(3)
print(m)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
